<?xml version="1.0" encoding="utf-8"?><Database Name="ShopLaptop" Class="ShopLaptopDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ShopLaptop;Integrated Security=True" SettingsObjectName="ShopLaptop.Properties.Settings" SettingsPropertyName="ShopLaptopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="MaLT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaBanTungSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThueVAT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KhuyenMai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTienTungSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" />
      <Association Name="Laptop_ChiTietHoaDon" Member="Laptop" ThisKey="MaLT" OtherKey="MaLT" Type="Laptop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhieuNhap" Member="ChiTietPhieuNhaps">
    <Type Name="ChiTietPhieuNhap">
      <Column Name="MaLT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNK" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaNhapTungSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThueVAT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTienTungSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Laptop_ChiTietPhieuNhap" Member="Laptop" ThisKey="MaLT" OtherKey="MaLT" Type="Laptop" IsForeignKey="true" />
      <Association Name="PhieuNhapKho_ChiTietPhieuNhap" Member="PhieuNhapKho" ThisKey="MaNK" OtherKey="MaNK" Type="PhieuNhapKho" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoiBaoHanh" Member="GoiBaoHanhs">
    <Type Name="GoiBaoHanh">
      <Column Name="MaGoiBH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGoiBH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTaChiTiet" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="GoiBaoHanh_HoatDongBaoHanh" Member="HoatDongBaoHanhs" ThisKey="MaGoiBH" OtherKey="MaGoiBH" Type="HoatDongBaoHanh" />
    </Type>
  </Table>
  <Table Name="dbo.GoiNangCap" Member="GoiNangCaps">
    <Type Name="GoiNangCap">
      <Column Name="MaGoiNC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGoiNC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhiNC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GoiNangCap_HoatDongNangCap" Member="HoatDongNangCaps" ThisKey="MaGoiNC" OtherKey="MaGoiNC" Type="HoatDongNangCap" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayMuaHang" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoTienThanhToanHoaDon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhuongThucThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThaiThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="MaHD" OtherKey="MaHD" Type="ChiTietHoaDon" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoatDongBaoHanh" Member="HoatDongBaoHanhs">
    <Type Name="HoatDongBaoHanh">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGoiBH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChiPhiSuaChua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTienHoTro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianBH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDauBH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="GoiBaoHanh_HoatDongBaoHanh" Member="GoiBaoHanh" ThisKey="MaGoiBH" OtherKey="MaGoiBH" Type="GoiBaoHanh" IsForeignKey="true" />
      <Association Name="KhachHang_HoatDongBaoHanh" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoatDongBaoHanh" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoatDongNangCap" Member="HoatDongNangCaps">
    <Type Name="HoatDongNangCap">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGoiNC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GoiNangCap_HoatDongNangCap" Member="GoiNangCap" ThisKey="MaGoiNC" OtherKey="MaGoiNC" Type="GoiNangCap" IsForeignKey="true" />
      <Association Name="KhachHang_HoatDongNangCap" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoatDongNangCap" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoCCCD" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoTienDaGD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDon" />
      <Association Name="KhachHang_HoatDongBaoHanh" Member="HoatDongBaoHanhs" ThisKey="MaKH" OtherKey="MaKH" Type="HoatDongBaoHanh" />
      <Association Name="KhachHang_HoatDongNangCap" Member="HoatDongNangCaps" ThisKey="MaKH" OtherKey="MaKH" Type="HoatDongNangCap" />
      <Association Name="KhachHang_TraGop" Member="TraGops" ThisKey="MaKH" OtherKey="MaKH" Type="TraGop" />
    </Type>
  </Table>
  <Table Name="dbo.Laptop" Member="Laptops">
    <Type Name="Laptop">
      <Column Name="MaLT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenHangLT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KhoiLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="HanBaoHanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MauSac" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DungLuongBoNho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManHinh" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="QuaTangKem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pin" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Laptop_ChiTietHoaDon" Member="ChiTietHoaDon" ThisKey="MaLT" OtherKey="MaLT" Type="ChiTietHoaDon" Cardinality="One" />
      <Association Name="Laptop_ChiTietPhieuNhap" Member="ChiTietPhieuNhap" ThisKey="MaLT" OtherKey="MaLT" Type="ChiTietPhieuNhap" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThaiHopTac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhaCungCap_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="MaNCC" OtherKey="MaNCC" Type="PhieuNhapKho" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Passwd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThaiTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
      <Association Name="NhanVien_HoatDongBaoHanh" Member="HoatDongBaoHanhs" ThisKey="MaNV" OtherKey="MaNV" Type="HoatDongBaoHanh" />
      <Association Name="NhanVien_HoatDongNangCap" Member="HoatDongNangCaps" ThisKey="MaNV" OtherKey="MaNV" Type="HoatDongNangCap" />
      <Association Name="NhanVien_PhieuNhapKho" Member="PhieuNhapKhos" ThisKey="MaNV" OtherKey="MaNV" Type="PhieuNhapKho" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhapKho" Member="PhieuNhapKhos">
    <Type Name="PhieuNhapKho">
      <Column Name="MaNK" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhapKho" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoTienThanhToanNhapKho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhuongThucThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThaiThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhieuNhapKho_ChiTietPhieuNhap" Member="ChiTietPhieuNhaps" ThisKey="MaNK" OtherKey="MaNK" Type="ChiTietPhieuNhap" />
      <Association Name="NhaCungCap_PhieuNhapKho" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuNhapKho" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraGop" Member="TraGops">
    <Type Name="TraGop">
      <Column Name="MaHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LaiSuatHangThang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TienTraTruoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianTraGop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayDaoHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhachHang_TraGop" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
</Database>